export enum ERoutesNamePermissions {
  AUTH_REGISTER = 'AUTH:REGISTER',
  AUTH_LOGIN = 'AUTH:LOGIN',
  ROLE_CREATE = 'ROLE:CREATE',
  ROLE_FIND_ONE = 'ROLE:FIND-ONE',
  ROLE_FIND = 'ROLE:FIND',
  ROLE_UPDATE = 'ROLE:UPDATE',
  ROLE_DELETE = 'ROLE:DELETE',
  PERMISSION_CREATE = 'PERMISSION:CREATE',
  PERMISSION_FIND_ONE = 'PERMISSION:FIND-ONE',
  PERMISSION_FIND = 'PERMISSION:FIND',
  PERMISSION_UPDATE = 'PERMISSION:UPDATE',
  PERMISSION_DELETE = 'PERMISSION:DELETE',
}
